-- ============================================================
--  APP D'ÉQUIPE DA'WAH — v3 : votes & commentaires sur les idées
--  Projet Supabase : lpvuklsxnrqliarwvmst. Tout scopé par "code". Realtime activé.
--  À exécuter UNE FOIS (après team-tables-v2.sql). Strictement additif. Idempotent.
--  Aucune modif des tables existantes — zéro impact sur les 168 récitations du groupe 0000.
-- ============================================================

-- VOTES (1 par frère par idée, valeur +1 ou -1, modifiable à tout moment)
create table if not exists public.team_idea_votes (
  id          bigint generated by default as identity primary key,
  code        text not null,
  idea_id     bigint not null references public.team_ideas(id) on delete cascade,
  member      text not null,
  value       int  not null check (value in (-1, 1)),
  created_at  timestamptz not null default now(),
  unique (code, idea_id, member)
);

-- COMMENTAIRES (fil chronologique sous chaque idée)
create table if not exists public.team_idea_comments (
  id          bigint generated by default as identity primary key,
  code        text not null,
  idea_id     bigint not null references public.team_ideas(id) on delete cascade,
  author      text,
  text        text not null,
  created_at  timestamptz not null default now()
);

create index if not exists team_idea_votes_code_idea_idx    on public.team_idea_votes(code, idea_id);
create index if not exists team_idea_comments_code_idea_idx on public.team_idea_comments(code, idea_id);

-- RLS : accès anon complet (groupe de confiance, scopé par code côté app)
alter table public.team_idea_votes    enable row level security;
alter table public.team_idea_comments enable row level security;

drop policy if exists anon_all on public.team_idea_votes;
create policy anon_all on public.team_idea_votes    for all to anon, authenticated using (true) with check (true);
drop policy if exists anon_all on public.team_idea_comments;
create policy anon_all on public.team_idea_comments for all to anon, authenticated using (true) with check (true);

grant all on public.team_idea_votes, public.team_idea_comments to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Realtime (ignore l'erreur si déjà ajouté)
do $$ begin
  begin
    alter publication supabase_realtime add table public.team_idea_votes;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.team_idea_comments;
  exception when duplicate_object then null;
  end;
end $$;
