-- ============================================================
--  APP D'ÉQUIPE DA'WAH — v6 : « Quoi de neuf » (releases + drafts validables)
--  Projet Supabase : lpvuklsxnrqliarwvmst. Tout scopé par "code". Realtime activé.
--  À exécuter UNE FOIS (après team-tables-v4.sql). Strictement additif. Idempotent.
--  Aucune modif des tables existantes — zéro impact sur les 168 récitations du groupe 0000.
-- ============================================================

-- RELEASES (drafts pré-écrits par l'IA, validés/publiés par Bilal)
create table if not exists public.team_releases (
  id            bigint generated by default as identity primary key,
  code          text not null,
  title         text not null,
  body          text,
  goto          text,                                        -- onglet cible (ex. 'ideas', 'videos', 'point'…)
  version       text,                                        -- ex. 'v6'
  commit_sha    text,                                        -- ex. '8f30351'
  status        text not null default 'draft' check (status in ('draft','published')),
  shipped_by    text,                                        -- auteur (toujours 'Bilal' en pratique)
  created_at    timestamptz not null default now(),
  published_at  timestamptz
);

-- LIAISON release ↔ idées résolues
create table if not exists public.team_release_ideas (
  id          bigint generated by default as identity primary key,
  code        text not null,
  release_id  bigint not null references public.team_releases(id) on delete cascade,
  idea_id     bigint not null references public.team_ideas(id)    on delete cascade,
  created_at  timestamptz not null default now(),
  unique (release_id, idea_id)
);

create index if not exists team_releases_code_status_idx     on public.team_releases(code, status);
create index if not exists team_releases_code_published_idx  on public.team_releases(code, published_at desc);
create index if not exists team_release_ideas_release_idx    on public.team_release_ideas(release_id);
create index if not exists team_release_ideas_idea_idx       on public.team_release_ideas(code, idea_id);

-- RLS : accès anon complet (cohérent avec le reste, scopé par code côté app)
alter table public.team_releases      enable row level security;
alter table public.team_release_ideas enable row level security;

drop policy if exists anon_all on public.team_releases;
create policy anon_all on public.team_releases      for all to anon, authenticated using (true) with check (true);
drop policy if exists anon_all on public.team_release_ideas;
create policy anon_all on public.team_release_ideas for all to anon, authenticated using (true) with check (true);

grant all on public.team_releases, public.team_release_ideas to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Realtime (ignore l'erreur si déjà ajouté)
do $$ begin
  begin
    alter publication supabase_realtime add table public.team_releases;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.team_release_ideas;
  exception when duplicate_object then null;
  end;
end $$;

-- Note : team_ideas.status est un text libre ; les idées résolues passent à 'livree'
-- côté app au moment du publishRelease. Aucune contrainte à modifier.
