-- ============================================================
--  APP D'ÉQUIPE DA'WAH — v4 : push notifications (app fermée)
--  Projet Supabase : lpvuklsxnrqliarwvmst. Tout scopé par "code". Realtime non requis (push géré via webhook + Edge Function).
--  À exécuter UNE FOIS (après team-tables-v3.sql). Strictement additif. Idempotent.
--  Aucune modif des tables existantes — zéro impact sur les 168 récitations du groupe 0000.
-- ============================================================

-- SOUSCRIPTIONS PUSH (Web Push API). 1 par couple (appareil, navigateur). Un même frère peut avoir N souscriptions (phone, desktop, tablette…).
create table if not exists public.team_push_subs (
  id          bigint generated by default as identity primary key,
  code        text not null,
  member      text not null,
  endpoint    text not null,
  p256dh      text not null,           -- clé pub ECDH côté client (base64url)
  auth        text not null,           -- secret auth (base64url)
  device_id   text,                    -- identifiant aléatoire stable par device (LS)
  user_agent  text,
  created_at  timestamptz not null default now(),
  unique (endpoint)                    -- une seule souscription par endpoint push
);

create index if not exists team_push_subs_code_idx   on public.team_push_subs(code);
create index if not exists team_push_subs_member_idx on public.team_push_subs(code, member);

-- RLS : accès anon complet (cohérent avec le reste du projet, scopé par code côté app)
alter table public.team_push_subs enable row level security;

drop policy if exists anon_all on public.team_push_subs;
create policy anon_all on public.team_push_subs for all to anon, authenticated using (true) with check (true);

grant all on public.team_push_subs to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
