-- ============================================================
--  APP D'ÉQUIPE DA'WAH — v12 : VISIOS (appels visio + agenda + fuseaux + présence)
--  Projet Supabase : lpvuklsxnrqliarwvmst. Tout scopé par "code".
--  100 % ADDITIF + snapshot. Aucune suppression, aucun recalcul. Idempotent.
--  - Ajoute team_members.tz (fuseau horaire IANA par frère, ex. "Indian/Reunion")
--  - Crée team_meetings (visios proposées : instant absolu UTC + fuseau organisateur)
--  - Crée team_meeting_rsvp (présence de chaque frère : présent/peut-être/absent + horaire dispo)
-- ============================================================

-- SNAPSHOT de sécurité (devoirs/membres jamais perdus — contrainte ferme de Bilal)
create table if not exists public.team_members_backup_20260625 as select * from public.team_members;

-- 1) FUSEAU HORAIRE par frère (auto-détecté côté app, modifiable en Réglages)
alter table public.team_members add column if not exists tz text;

-- 2) VISIOS proposées
create table if not exists public.team_meetings (
  id            bigint generated by default as identity primary key,
  code          text not null,
  title         text not null,
  starts_at     timestamptz not null,        -- INSTANT ABSOLU (UTC) — chaque frère l'affiche dans SON fuseau
  duration_min  int  not null default 60,
  video_url     text,                         -- lien du visio (Meet/Zoom/Jitsi…)
  note          text,
  organizer_tz  text,                         -- fuseau dans lequel l'organisateur a saisi l'heure (pour l'heure "de référence")
  status        text not null default 'proposed',  -- proposed | confirmed | cancelled
  created_by    text,
  created_at    timestamptz not null default now()
);
create index if not exists team_meetings_code_idx  on public.team_meetings(code);
create index if not exists team_meetings_start_idx on public.team_meetings(code, starts_at);

-- 3) PRÉSENCE (1 ligne par frère et par visio)
create table if not exists public.team_meeting_rsvp (
  id          bigint generated by default as identity primary key,
  code        text not null,
  meeting_id  bigint not null,
  member      text not null,
  status      text not null default 'present', -- present | maybe | absent
  note        text,                            -- ex. "dispo seulement après 21h chez moi"
  updated_at  timestamptz not null default now(),
  unique (meeting_id, member)
);
create index if not exists team_meeting_rsvp_mid_idx on public.team_meeting_rsvp(meeting_id);
create index if not exists team_meeting_rsvp_code_idx on public.team_meeting_rsvp(code);

-- RLS : accès anon complet (cohérent avec tout le projet, scopé par code côté app)
alter table public.team_meetings     enable row level security;
alter table public.team_meeting_rsvp enable row level security;

drop policy if exists anon_all on public.team_meetings;
create policy anon_all on public.team_meetings     for all to anon, authenticated using (true) with check (true);
drop policy if exists anon_all on public.team_meeting_rsvp;
create policy anon_all on public.team_meeting_rsvp for all to anon, authenticated using (true) with check (true);

grant all on public.team_meetings     to anon, authenticated;
grant all on public.team_meeting_rsvp to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- REALTIME : ajoute les 2 tables à la publication (silencieux si déjà présentes / publication "for all tables")
do $$ begin
  begin alter publication supabase_realtime add table public.team_meetings;     exception when others then null; end;
  begin alter publication supabase_realtime add table public.team_meeting_rsvp; exception when others then null; end;
end $$;

-- vérif : le snapshot membres doit être identique à la source
select 'members'    q, count(*) n from public.team_members
union all
select 'members_bk' q, count(*) n from public.team_members_backup_20260625;
